#branches: [master, test]
branches: [feature-drone]
matrix:
  include:
  - HOST: libtest1.csc.fi
    FOO: bar
    USER: aleph
    DIRECTORY: /exlibris/aleph/u23_3/alephe/apache/htdocs/aleph-record-load-api/app
    TAR_EXEC: /usr/sfw/bin/gtar
    INSTANCE: test
pipeline:
# Test
  test-deploy:
    image: quay.io/natlibfi/drone-plugin-scp
    host: ${HOST}
    username: ${USER}
    target: ${DIRECTORY}
    source: ['.']
    rm: true
    tar_exec: ${TAR_EXEC}    
    secrets:
    - source: ssh_key_${HOST}
      target: ssh_key
    when:
      #branch: test
      branch: feature-drone
      matrix:
        INSTANCE: test
# Production
    image: quay.io/natlibfi/drone-plugin-scp
    host: ${HOST}
    username: ${USER}
    target: ${DIRECTORY}
    source: ['.']
    rm: true
    tar_exec: ${TAR_EXEC}    
    secrets:
    - source: ssh_key_${HOST}
      target: ssh_key
    when:
      branch: master
      matrix:
        INSTANCE: production
