---
kind: pipeline
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host:
      from_secret: host_production
    username:
      from_secret: username_production
    key:
      from_secret: ssh_key_production
    rm: true
    source:
    - "README.md"
    - "package.json"
    - "src/*"
    target: /exlibris/linnea/node-aleph-record-load-api/app/
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_production
    username:
      from_secret: username_production
    key:
      from_secret: ssh_key_production
    script:
    - "cd /exlibris/linnea/node-aleph-record-load-api/app/"
    - "npm install && npm run test && npm run build"
trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    rm: true
    source:
    - "README.md"
    - "package.json"
    - "src/*"
    target: /exlibris/linnea/node-aleph-record-load-api/app/
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    script:
    - "cd /exlibris/linnea/node-aleph-record-load-api/app"
    - "npm install && npm run test && npm run build"
trigger:
  branch:
  - python-to-node
  - dev
  - test

---
kind: secret
name: host_test
data: wTd7hNNzXvIAbcLcdh+v2nJah6v+FaqzW+lh1JGsIneq8uC6iDwFOezZkwwm
---
kind: secret
name: username_test
data: m5NHENJ7mevnkpbyMjOrrB7XJMet55n8p6FRKeom4BYa
---
kind: secret
name: ssh_key_test
data: 'pYZZOWCCeuJuyfYxoy/8vFrWxc8dOcW9uAeXqsZWWON/oKZ+MixoMnGWrWLcALiKE/xA0Lba1ST0sKvnVO9tDntQ798ayAhsBrfp8NJkDQKEiMfCqgPD3N2us7mlaKLXPxHRXv5EFvR3Z4kFQxrSer3a5OxdTHkmYNkgcS0e0eDIzxW7vox4r6WFNDcA+5VKaViSCFhc2rPm/S5XhmXEUXjlt6UGym1OPMxH64wRhl4Q2OBsxSvEZzhHk61HaLdd1DrEv16NuH0YxtWTNL5+ASH5a5ww+J9tgWYrns7546RVfDVtlQfQXdyeK33llYIBxmzTaJhqtbo4WPRi4s9Lzm68nhIIiSDZNVoY4FMUOWjiB2YjulTIWFBe5cx4uXNZuaGx9cY+Zxm2//iojxwN+/ei1quleCqZ2gAxXpKoztq6oF45E7cKyU3McWV9oMAk+P8XA+zZ21j1J92pCPpMgWyc2M28kMD9Rv5+a7J6gtGlz6yHihVihhy8rbMMp0BxCTHLawIBytArMB33zeGUhxpBVcU4sUqE0AilvinQpy4Pp0x/eb/s2/U+XW3W75VFA+TdrSJZf2roIJZHjVkamj7hbO3aGRMSUwZ9z6s2lSBWf6NpnYKX3dmNGiaoTgcjh8mRL4PWpYhWhDQDgbafOHqNd85EhhUhO1U6eaL4e0LfR1EV8ByvLLLIYaI/uwXuxaPbvsc/QiT79eLe9m9LwPqyGIa/quu4KMYxYVle7XEwtk7ANfQFQjPd6iX8A3nhhhE99J3Tc+z5ufWyUI26ILhImyH9GQR8Z8MdWdyRTr46WomSMuMeLmaUGFjWSeePz8+KrsdBaEIFJOaQTmnLcQ0SRGlOlOxt2+3ux5eUDIh1ylyB+v7GM3Mb6nq01qlogmOggVpvjj023khZRPZ4YYLwGxlLhQhZm41BJxeRUQqIp1tXBy2XJdFUVZIVa8/czO5wv2QO9vkHeoCt3xoZmdLfzBMXZSPUvcOWH2TIHo0xG+e25ZLRmF9E16pvoxk2RLBdS3Pdo2v4lRiWg41s4AYZRjSg8pFciYyPH5PrggGTVuYPje8tzjOYFB0io3dschTG6bWFiy+EmsN3WcoDPifZ5SJLqXoV8MBd+7s+KK53nfHsGTXeP/N9m/4uvlPQQHy8zYRDV6l2zwNFFs9IOlVznfi7ru3xMM/10G0hVr0dp8F4s7SDvxM3LZMUotT/TuCYh7Lfvn1EfXm2yQyDoAkIS33Cy6geNtPJh6Egit9M9ysO99k4hY1KbWKjMP8M4XmG03t6AvUoh1UJz7QwYRqRimy8K/Duuwnzn1xool4Bp5EnMj1J4shps9sNgrEqbPWVlERJDIu9XugljtyY/UmfuH8ynmjwxkqBqVXzM+bUmpw1Uq0rMewJGDCyOjxLbcINAPGUTyVBdlmP/qEAcflnFKv8EltVnKq6HLirb7Wdjn2BTqZvFvh60BndnOD4uxb/Gq+ojKadYQ5eNvrEvB7MOAbar17U2uKrydDkeponQjzjDbMI9NOLnVrbNwkKuFaBKWdEUY9/lDO2+cyGQ1MmR1i6Mvv3CJGuY8dqHSn6QEd6GadexnTpmhKKj1WuVSwAJMU2twBVLMJ+mfmOQ0KqsxAcOKJF2gpDhREjS+maaiSfzJ76U7htrf45s0RKhGRkLrtZf35gxnPoJww9UDWGgsUeVDJfvGfVjO5ShKycyda198wbB9KOdXr3N55qs3shccFLbceR2KEbm9hsEhQo0zJVr1Ow2r5SVZ79wd2rykvH45tC7KiocalDS/fvi/EPxEY5Um+vVDc3hu0zSdrGao2X8VqBY3Q0gpmDYQN+gw35RIe8rcQJC5YEJ5IdQdt7/jzJ7kpd0xZBWA6Cf4cvMZoC5bJeRBSX/juVe4yukvSsc6tp2lV3o84o65igaNPs7QzCND7XS6MQa1pP9tJBXWYSnVj1/DIraGIbBa6iQ5aij3/Y+Y/8MZMUT5vT94VmCAxqYnSv1M5Qy48D42x8pv+6bj527DDjdId6YvogwMQnbiAJw+VuoiRdJ+81yhRX+Mw2dN6U8UGeKkBVvlJFOaDTkRMMbcIoMWfrORd0U5yd6SNPPicFZESb5P4gPiKcqGD4pslxJGSBTwpx/neLHvnMa9Sg8MIpQd+urrFLu/pdmYw5VQxgjk7uiMYzT/vKmhytWZmbXaiUYCTmVKXbOO+mqzi7OjcBPwzott2lMYvz/iW5jAOIDsQ1cFP13hyIIWx6HCzrJcp0LObKet8IpyZ18nJvhjSclFQBEWk3sWak/a8oP2jeqRk3DWQOL7I9sr9p3aV6yobBJdEkxTrnX1ybdFrHHCLkTLBrWBVHLt6a0P25FrGVH/WqWtOnXSmmfR4KL9LRDQ0uolf0IfyI6JngCEJLHRANf/Ln16diTSn2g+ehV83rayECwampZVyOd1diD8hVtpX6TXQKrcxtxVmhppHAvGMXb/HkWO9Ol3RZrZdMQ+hV4KVDS21Y8/UBYuw251pqTC+167Ny0g3+ZAKe0H8B6NDs3G0eUVe8ZUXvGaiSkomwNY0+eZrEANBbeeT5mz+37zA1CaYTKDWk//6UjwV/1Jh7XZmOzZM90Qzv7vWeOkviUBmVO65aCO6m5nzMjXdGkWYnaa12aaD5D9kNkWJOuf+nio1QcA+vBMJ8NwhJUOhLM4dGEwA1+MesfB9g/Wp97l5hwlJTZX+qo+CqmbwswSw3QBYAWWe0KQLjSi9OotJ91RD9aRApx+3zr7QSa4rwldTm/vibH0pfAKTxs04qzIlGU0l6CWRjhX0PyE1Wd3BVZUAVQi48UgL03DTdPH9OJNjCwmFGu426VRW+ETeBLhThERPKtw4lZJotjzNGVI9E5UGI310T/ms+tT5Kr73I8VhMSwP447MEKW9f8mpX96BNwoU8OUmMwP9bVR1nslAR2vAWOl6AyYBbn5j8BKSEU5nudXdFWlitHBsu1UcmO3jSlOz5cOHdi2gKT2FJt1fe/iJP97mYnL6e3dvOfI6UU+71'
---
kind: signature
hmac: b5519f113f4bd39ce47b27abdaf4306023a76e6de9d3665457f47b3c943eeed3

...
