kind: pipeline
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    script:
    - "cd /exlibris/linnea/node-aleph-record-load-api/"
    - "git clone https://github.com/NatLibFi/aleph-record-load-api"
    - "npm install"
  when:
    branch: [master, test, python-to-node]
    event: push
event: [push]
