---
kind: pipeline
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host:
      from_secret: host_production
    username:
      from_secret: username_production
    key:
      from_secret: ssh_key_production
    rm: true
    source:
    - "README.md"
    - "package.json"
    - "src/*"
    target: /exlibris/linnea/node-aleph-record-load-api/app/
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_production
    username:
      from_secret: username_production
    key:
      from_secret: ssh_key_production
    script:
    - "cd /exlibris/linnea/node-aleph-record-load-api/app/"
    - "npm install && npm run test && npm run build"
trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: quay.io/natlibfi/drone-plugin-scp
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    rm: true
    source:
    - "README.md"
    - "package.json"
    - "src/*"
    target: /exlibris/linnea/node-aleph-record-load-api/app/
- name: npm install
  image: quay.io/natlibfi/drone-plugin-ssh
  settings:
    host:
      from_secret: host_test
    username:
      from_secret: username_test
    key:
      from_secret: ssh_key_test
    script:
    - "cd /exlibris/linnea/node-aleph-record-load-api/app"
    - "npm install && npm run test && npm run build"
trigger:
  branch:
  - python-to-node
  - dev
  - test

---
kind: secret
name: host_test
data: wTd7hNNzXvIAbcLcdh+v2nJah6v+FaqzW+lh1JGsIneq8uC6iDwFOezZkwwm
---
kind: secret
name: username_test
data: m5NHENJ7mevnkpbyMjOrrB7XJMet55n8p6FRKeom4BYa
---
kind: secret
name: ssh_key_test
data: 2Fxrs7kKvc24yfhb6L7Az++SGGsZzZ5ARHqydb5HzvfPj8bxdmmTbnfOHX4y198mzjfupUGwa74wcdYr+FlrQjZSCJLMA+JIBAF1pSV6VvijqWu9XlHhw+OYPzuQcDZrRk2AonjSpkiWrk9dqp7j1RjAW8KeL0ziumVM2DpD6j08IaukH1t9eODaD/Of0//i48B9dNUtH8kbdjzeQ4XM8VhB7fPYWxpbnS5Qhm3U8epPqjhj0rRDUwnFCdDdQ1VvGq7S/XWQ7VB7XiFtHR7DEVGIpmWUZ9RRVT4NqLPHXhB5/qCgcBD8Q4FLmIvge/ZIn+9/Pag3CifjzZOFhmkoYJDIQD4uZyHoNeUFaNkCMJgfZRiv5PaW6SB8Bu1Ny4Q+HoXM19k28PUc2G+hS//3Th3OBJhzpY6YqpFo8+dSg/mrr5UiK7DecBSBJQ2vk9xBFTySDzilM0uaEICsu4HkQ81OCseuH4ac63jIQ9+JVodMhF7ggDbuQ9tJYB9sZA7AwlisIVHomg8Jbinx4Dm/hw55GAprUCvA46bP5JWDgS/gqH3+40YsEPcLGFyc8rtdbKNhluC9v/PCenpyS/nr2TMvqibtcrQHxXX/n5U3vy5Mpq45WmJCKtGVl1yex6hLifmBaeXN+8rVepCjGbzjY1/xOx5/IT/gYFnhNMYPQc3TShmISTvvy3ujMxzoN+kkO3PmN9XIfgpAnNLsR6hqzTGimWVOANIC/eHmLdL15MNx7EhOZ1fRkjXExaau5kbZ6C3Kg1IOcyVbge92Q9FLPApqjhKzQzAQM0Tw2uNrdLuk5ljQ0s8kbeZ9JvRSuum9L4STJjFVy8hXnkh0ySXf1Ad7MTD7TuGgxMhlZC2jD8ep3BpO3IjEQudb1fczstZAD4PJ5EX3veg6BnsQZKFeQj+XjPOV5QgQr9p8WdkakfxTgQcTLQ5uTnvB+3FvNS1nmAI3+OfBiflrk2Lf46KayD2fSQAx1Wwm6+5uCmbjWaEaJdfLUGoREIcKFxXXFLVc5pLvB4X5gKifRPW4JQDj9iRI4zqf46eiZ0YfjX3y1GYdBeJ0R2S8Msv7+OJczl3UGoqpP2Zk/gSnrP1gtDaNiPQmRXaVn5UXNXGfF76vCMEkhQttfkszA26gNZJwYV/IvWBy4lpFzdtGEZOmw0ZzjAfNkFz7j1ZzReiTFMN6/zeNCP27F4fCBUwbj9tWGYIyEgoJeKcvSSVPJ+2in7imOZD6cWV4s657fyLnhrv84jrCBb+fvZ69E66SzjlbkiY2d2cpD19Pb7uJmJ1fnIjOgNXuNmehbx1BxgRg2DClU3dpwTrcniSIn2KSRmdjUS00+a4LCTNBQTBxUtBq3hJB4ACyHenfy8C0dDhcCbZmUwhhZ4/asogCJWYkACjuRHjiAvwoY5JRDHQtu94LZAFP8NkPSX8bEW/a9fwEHV5w//WLCLwmD9GWT0km7owPkqyaDR3Bc3Da/5f41WYkBiKyRLvpRQh+6gHMGNxWJI2QT+rHoWnid+UsZBXZzMnUnPI3CkQAcEwsqbIkcJCNCsSnI9CSIiwFC15WqqE1VAFK2qZ3Esh1SEV0nnikXJrbbdYF3/x+tcxeQ5qrAz79yit3M0NXA5QnIn3pBKx2uWuJHxZUGACZTmSFzbOuIUWoKWFvw4NvipUN7m79Lj8YLe65tn8xEYx9FzFIGwgjCPoU3QbWdUwdDYSu4k+LzcMGxcTV00MO2hXNvNp3IUSyrNHpKybkGsGSUY7DT2Jl0NZFHNPbEAlKJpSGR/4eQU9sTdmsEwVbw2BGJVoqES7PzUMkrg5c8H/RQin1TuXVMw7E4bif0o0FKogeEZVGBdaJQKUDJrlbU+AeSMu8o60lZ1D53lNE+RSkbfnn2CiK3tlcRrI1kG7O1sOD7UvwJL7F5INo9yjfoNn21YwdTBoiGN8AZ0QCX6SSjulcT6TRzRCa/s+ZrCH+Mm0Q/9kLMYKrsOcM9AU1DB/b3U5xKz35ItGO+yye+qnnpgCOMqlLOH3ktmtlPVFvt0O6pOOgT7bLXvr4V0UU8Ope+scWn7B6ajBh4iwgLu+aqcGNow0h+Y58TF+HDNKUdBngjdMq/Ixg51UBZURlNIjak8/28ty9CKywRaENuaL89lZqoDPqZ9z3shu7/qNk/LYkbIQX8u8ylzWkvc8gtgXV4HTX8jwjOolkoRPbpiG93E5EqE8wTV/I+kbrf95810geYDF49maw8kErQXF2nn9dEmyQBKifuvnvNGPHFiPBtI9/p0AOPnaK2BMyj6205myGr+9BVkcTviib7Bhqr5OPccXfORo6ZGA+fP+CwiOyzmzzLUktyhOJUjmXbVbnkCYZGxRnTIMtsx5arr8r0o9zdQ8aEHGc10zz7BDwyN7Qj8r+0p7RqJMdMAw6Pu7vxkbWvT2SLBJgSbCLAMwdMfq2T0WQ9FsxqWqRMlESP0J88YCvdkKMYyvfnOoOacBDOPto7Y0dW6u+ncTEGvv329CC4s+hDf8aY5CUjrigs24mOQSdnLVeZ9cAdBjVzfahq77MUe01MVYTGFVJzSlkxmYtCm43mnXGEBicLCsoOvk9SUZPGiQfvrPE0EmJjlLaa0bP2wCd/ChuchX5uBebhABq20v4wjjJqVKjfqvZr7ywVFsFJlNgFqUDNQLign2XNifsm6x/XVh+ABiZ/qLRx8jkjJL30vIJ5VPaLOJV+cKgFCU6WRin+94CNnWyn1jqy/WCKL49ayS7xBuSLB/WN5k0UfIUJL4TkYXVu0SKurxwBl9ivpbEzBxpIkiZjwgUpWPAMi9Iv4J37icHdJEsxYbFXYDsxZXZPF1o+Klrv1FtquJufcmsXMc6uRkOFtsIjj8gdBjpad8/KxHcHIvKXYO4u70y3mnDKyFdKp/MIJYu5ScN3loeK8hv09ITqjE2A1vXPidZiUcrYdnuRjetgMEqB4pWqL8KYeYyaYu/55PSAUECKtqjl2ZbOi/9JmnCbJD9fxfZrOIUAPY/gxmcY1o0UZ9peQ5F
---
kind: signature
hmac: 805cffdd19baf904efa1d79b6bd5d615e9745e56883f7a5fc2afbf989da80578

...
